[package]
name = "alloy-mev"
version = "0.1.1"
authors = ["leruaa"]
license = "MIT"
edition = "2021"
readme = "./README.md"
documentation = "https://docs.rs/alloy-mev"
repository = "https://github.com/leruaa/alloy-mev"
homepage = "https://github.com/leruaa/alloy-mev"
description = """
Easily send transaction bundles using Alloy.
"""

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest"]

[dependencies]
alloy = { version = "0.1.3", features = [
    "rpc",
    "rpc-client",
    "json-rpc",
    "rpc-types",
    "rpc-types-mev",
    "rpc-types-eth",
    "network",
    "providers",
    "transports",
    "transport-http",
    "signers",
] }
serde = "1.0"
hyper = { version = "1.1", features = ["client"], optional = true }
tower = "0.4"
reqwest = { version = "0.12", optional = true }
url = "2.5"
serde_json = "1.0"
async-trait = "0.1"

[dev-dependencies]
dotenv = "0.15"
tokio = { version = "1", features = ["rt", "macros"] }
alloy = { version = "0.1.3", features = [
    "rpc-client",
    "consensus",
    "signer-local",
] }

[patch.crates-io]
alloy = { path = "../alloy/crates/alloy", features = ["full"] }
